let lU, uU, cU, hU
;((uU = lU || (lU = {}))[(uU.PLANE_LAYER = 0)] = 'PLANE_LAYER'),
  (uU[(uU.SHADOW_PLANE = 1)] = 'SHADOW_PLANE'),
  (uU[(uU.BASE_MAP_LAYER_BOTTOM_STROKE = 2)] = 'BASE_MAP_LAYER_BOTTOM_STROKE'),
  (uU[(uU.BASE_MAP_LAYER_EXTRUDE_MESH = 3)] = 'BASE_MAP_LAYER_EXTRUDE_MESH'),
  (uU[(uU.BASE_MAP_LAYER_PROVINCE_MESH = 4)] = 'BASE_MAP_LAYER_PROVINCE_MESH'),
  (uU[(uU.DISTRICT_LAYER_PROVINCE_MESH = 5)] = 'DISTRICT_LAYER_PROVINCE_MESH'),
  (uU[(uU.BASE_MAP_LAYER_PROVINCE_STROKE = 6)] =
    'BASE_MAP_LAYER_PROVINCE_STROKE'),
  (uU[(uU.BASE_MAP_LAYER_COUNTRY_STROKE = 7)] =
    'BASE_MAP_LAYER_COUNTRY_STROKE'),
  (uU[(uU.BASE_MAP_LAYER_INNERSHADOW_MESH = 8)] =
    'BASE_MAP_LAYER_INNERSHADOW_MESH'),
  (uU[(uU.BOUNDARY_STREAMER_MESH = 9)] = 'BOUNDARY_STREAMER_MESH'),
  (uU[(uU.POLYGON_MESH = 10)] = 'POLYGON_MESH'),
  (uU[(uU.POLYGON_STROKE = 11)] = 'POLYGON_STROKE'),
  (uU[(uU.PATH_LAYER = 12)] = 'PATH_LAYER'),
  (uU[(uU.PATH_LAYER_DIR = 13)] = 'PATH_LAYER_DIR'),
  (uU[(uU.BREATH_POINT_LAYER_OUTER_MESH = 14)] =
    'BREATH_POINT_LAYER_OUTER_MESH'),
  (uU[(uU.BREATH_POINT_LAYER_INNER_MESH = 15)] =
    'BREATH_POINT_LAYER_INNER_MESH'),
  (uU[(uU.BUBBLE_LAYER_MESH = 16)] = 'BUBBLE_LAYER_MESH'),
  (uU[(uU.POINT_HEATMAP3D_LAYER = 17)] = 'POINT_HEATMAP3D_LAYER'),
  (uU[(uU.HEXAGON_HEATMAP = 18)] = 'HEXAGON_HEATMAP'),
  (uU[(uU.LIGHT_BAR_LAYER = 19)] = 'LIGHT_BAR_LAYER'),
  (uU[(uU.BAR_LAYER = 20)] = 'BAR_LAYER'),
  (uU[(uU.FLY_LINE_LAYER = 21)] = 'FLY_LINE_LAYER'),
  (uU[(uU.STREAM_LAYER = 22)] = 'STREAM_LAYER'),
  (uU[(uU.PARTICLE_LAYER = 23)] = 'PARTICLE_LAYER'),
  ((hU = cU || (cU = {}))[(hU.POI = 0)] = 'POI'),
  (hU[(hU.ATTACH_LAYER_BACKGROUND_MESH = 1)] = 'ATTACH_LAYER_BACKGROUND_MESH'),
  (hU[(hU.ATTACH_LAYER_FILL_MESH = 2)] = 'ATTACH_LAYER_FILL_MESH'),
  (hU[(hU.ATTACH_LAYER_STROKE_MESH = 3)] = 'ATTACH_LAYER_STROKE_MESH'),
  (hU[(hU.ATTACH_LAYER_BORDER_MESH = 4)] = 'ATTACH_LAYER_BORDER_MESH'),
  (hU[(hU.ATTACH_LAYER_POI = 5)] = 'ATTACH_LAYER_POI')

export {lU, uU, cU, hU}
